#!/bin/bash

function agents {
    agent_array=(Mozilla "Google Chrome" Opera Safari "Internet Explorer" "Microsoft Edge" "Crawler and bot" "Library and net tool")
    echo ${agent_array[$(($RANDOM % 8))]}
}